_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "output/pretrain_on_task0.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.5
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy"
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  IMS_PER_BATCH: 8
  STEPS: (5000, 7500, 15000, 17500)
  MAX_ITER: 10000
  BASE_LR: 0.002
  CHECKPOINT_PERIOD: 2000
DATALOADER:
  NAME_OLD_CLASSES: [ 'Container', 'cell-container', 'Dredger']
  NAME_NEW_CLASSES: [ 'ore-oil', 'Fishing', 'LawEnforce' ]
  SUP_PERCENT: 100.0
  RANDOM_DATA_SEED: 0
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("my_train",)
  TEST: ("my_val",)
SEMISUPNET:
  Trainer: "ubteacher"
  BURN_UP_STEP: 500
  EXEMPLAR_MINING: True
  EXEMPLAR_REPLAY: True
  MIXUP: False
  SCENE_LEVEL: True
  INSTANCE_LEVEL: True
  LOGIT_LEVEL: True
TEST:
  EVAL_PERIOD: 1000
